name: Build

on:
    push:
        branches: [ dev, master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: cargo clippy --all-targets --all-features --release --verbose

    Build:
        needs: Lint
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019, windows-2016]

        steps:
          - uses: actions/checkout@v2

          - name: Build
            run: cargo build --release --verbose
